import type { Preset, PresetCategory } from '@/types';
import { BRAINWAVE_COLORS } from './constants';

export const PRESETS: Preset[] = [
  // Focus (Beta/Gamma)
  {
    id: 'deep-focus',
    name: 'Deep Focus',
    category: 'focus',
    icon: '\u{1F9E0}',
    description: 'Sustained concentration for deep work',
    carrierFreq: 200,
    beatFreq: 16,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 16 Hz',
    defaultDuration: 25,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.beta,
  },
  {
    id: 'study-flow',
    name: 'Study Flow',
    category: 'focus',
    icon: '\u{1F9E0}',
    description: 'Background focus for reading and study',
    carrierFreq: 250,
    beatFreq: 14,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 14 Hz',
    defaultDuration: 45,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.beta,
  },
  {
    id: 'creative-spark',
    name: 'Creative Spark',
    category: 'focus',
    icon: '\u{1F9E0}',
    description: 'Open, creative thinking and ideation',
    carrierFreq: 180,
    beatFreq: 10,
    brainwaveState: 'alpha',
    brainwaveLabel: 'Alpha \u00B7 10 Hz',
    defaultDuration: 20,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.alpha,
  },
  {
    id: 'problem-solving',
    name: 'Problem Solving',
    category: 'focus',
    icon: '\u{1F9E0}',
    description: 'Heightened information processing',
    carrierFreq: 220,
    beatFreq: 40,
    brainwaveState: 'gamma',
    brainwaveLabel: 'Gamma \u00B7 40 Hz',
    defaultDuration: 15,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.gamma,
  },

  // Sleep (Delta/Theta)
  {
    id: 'fall-asleep',
    name: 'Fall Asleep',
    category: 'sleep',
    icon: '\u{1F634}',
    description: 'Gentle descent into sleep',
    carrierFreq: 150,
    beatFreq: 3,
    brainwaveState: 'delta',
    brainwaveLabel: 'Delta \u00B7 3 Hz',
    defaultDuration: 30,
    fadeIn: 3,
    fadeOut: 2,
    color: BRAINWAVE_COLORS.delta,
  },
  {
    id: 'deep-sleep',
    name: 'Deep Sleep',
    category: 'sleep',
    icon: '\u{1F634}',
    description: 'Sustained deep, dreamless sleep',
    carrierFreq: 120,
    beatFreq: 1.5,
    brainwaveState: 'delta',
    brainwaveLabel: 'Delta \u00B7 1.5 Hz',
    defaultDuration: 60,
    fadeIn: 3,
    fadeOut: 2,
    color: BRAINWAVE_COLORS.delta,
  },
  {
    id: 'power-nap',
    name: 'Power Nap',
    category: 'sleep',
    icon: '\u{1F634}',
    description: 'Quick restorative rest',
    carrierFreq: 180,
    beatFreq: 5,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 5 Hz',
    defaultDuration: 20,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'insomnia-relief',
    name: 'Insomnia Relief',
    category: 'sleep',
    icon: '\u{1F634}',
    description: 'Calm a racing mind for sleep',
    carrierFreq: 136,
    beatFreq: 2.5,
    brainwaveState: 'delta',
    brainwaveLabel: 'Delta \u00B7 2.5 Hz',
    defaultDuration: 45,
    fadeIn: 3,
    fadeOut: 2,
    color: BRAINWAVE_COLORS.delta,
  },

  // Meditation (Theta/Alpha)
  {
    id: 'mindfulness',
    name: 'Mindfulness',
    category: 'meditation',
    icon: '\u{1F9D8}',
    description: 'Present-moment awareness',
    carrierFreq: 200,
    beatFreq: 7,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 7 Hz',
    defaultDuration: 20,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'transcendental',
    name: 'Transcendental',
    category: 'meditation',
    icon: '\u{1F9D8}',
    description: 'Deep transcendent meditation',
    carrierFreq: 136,
    beatFreq: 4.5,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 4.5 Hz',
    defaultDuration: 30,
    fadeIn: 3,
    fadeOut: 2,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'loving-kindness',
    name: 'Loving Kindness',
    category: 'meditation',
    icon: '\u{1F9D8}',
    description: 'Heart-centred compassion practice',
    carrierFreq: 264,
    beatFreq: 8,
    brainwaveState: 'alpha',
    brainwaveLabel: 'Alpha \u00B7 8 Hz',
    defaultDuration: 15,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.alpha,
  },
  {
    id: 'body-scan',
    name: 'Body Scan',
    category: 'meditation',
    icon: '\u{1F9D8}',
    description: 'Progressive body awareness',
    carrierFreq: 180,
    beatFreq: 6,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 6 Hz',
    defaultDuration: 25,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.theta,
  },

  // Relaxation (Alpha/Theta)
  {
    id: 'stress-relief',
    name: 'Stress Relief',
    category: 'relaxation',
    icon: '\u{1F60C}',
    description: 'Rapid stress reduction',
    carrierFreq: 200,
    beatFreq: 10,
    brainwaveState: 'alpha',
    brainwaveLabel: 'Alpha \u00B7 10 Hz',
    defaultDuration: 15,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.alpha,
  },
  {
    id: 'anxiety-calm',
    name: 'Anxiety Calm',
    category: 'relaxation',
    icon: '\u{1F60C}',
    description: 'Soothe anxious thoughts',
    carrierFreq: 170,
    beatFreq: 7.5,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 7.5 Hz',
    defaultDuration: 20,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'tension-release',
    name: 'Tension Release',
    category: 'relaxation',
    icon: '\u{1F60C}',
    description: 'Physical and mental tension relief',
    carrierFreq: 150,
    beatFreq: 5.5,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 5.5 Hz',
    defaultDuration: 15,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'wind-down',
    name: 'Wind Down',
    category: 'relaxation',
    icon: '\u{1F60C}',
    description: 'Evening transition to rest',
    carrierFreq: 190,
    beatFreq: 9,
    brainwaveState: 'alpha',
    brainwaveLabel: 'Alpha \u00B7 9 Hz',
    defaultDuration: 20,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.alpha,
  },

  // Energy (Beta/Gamma)
  {
    id: 'morning-boost',
    name: 'Morning Boost',
    category: 'energy',
    icon: '\u{26A1}',
    description: 'Energise your morning',
    carrierFreq: 250,
    beatFreq: 18,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 18 Hz',
    defaultDuration: 10,
    fadeIn: 1.5,
    fadeOut: 1,
    color: BRAINWAVE_COLORS.beta,
  },
  {
    id: 'afternoon-revival',
    name: 'Afternoon Revival',
    category: 'energy',
    icon: '\u{26A1}',
    description: 'Beat the afternoon slump',
    carrierFreq: 230,
    beatFreq: 15,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 15 Hz',
    defaultDuration: 10,
    fadeIn: 1.5,
    fadeOut: 1,
    color: BRAINWAVE_COLORS.beta,
  },
  {
    id: 'pre-workout',
    name: 'Pre-Workout',
    category: 'energy',
    icon: '\u{26A1}',
    description: 'Physical activation and drive',
    carrierFreq: 280,
    beatFreq: 25,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 25 Hz',
    defaultDuration: 10,
    fadeIn: 1.5,
    fadeOut: 1,
    color: BRAINWAVE_COLORS.beta,
  },
  {
    id: 'confidence',
    name: 'Confidence',
    category: 'energy',
    icon: '\u{26A1}',
    description: 'Self-assurance and presence',
    carrierFreq: 200,
    beatFreq: 20,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 20 Hz',
    defaultDuration: 15,
    fadeIn: 1.5,
    fadeOut: 1,
    color: BRAINWAVE_COLORS.beta,
  },

  // Therapy (Various)
  {
    id: 'pain-relief',
    name: 'Pain Relief',
    category: 'therapy',
    icon: '\u{1F3AF}',
    description: 'Frequency support for pain management',
    carrierFreq: 174,
    beatFreq: 4,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 4 Hz',
    defaultDuration: 30,
    fadeIn: 3,
    fadeOut: 2,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'headache-ease',
    name: 'Headache Ease',
    category: 'therapy',
    icon: '\u{1F3AF}',
    description: 'Soothing relief for headaches',
    carrierFreq: 160,
    beatFreq: 6,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 6 Hz',
    defaultDuration: 15,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'tinnitus-mask',
    name: 'Tinnitus Mask',
    category: 'therapy',
    icon: '\u{1F3AF}',
    description: 'Gentle masking for tinnitus',
    carrierFreq: 400,
    beatFreq: 10,
    brainwaveState: 'alpha',
    brainwaveLabel: 'Alpha \u00B7 10 Hz',
    defaultDuration: 30,
    fadeIn: 3,
    fadeOut: 2,
    color: BRAINWAVE_COLORS.alpha,
  },
  {
    id: 'adhd-focus',
    name: 'ADHD Focus',
    category: 'therapy',
    icon: '\u{1F3AF}',
    description: 'Sustained attention support',
    carrierFreq: 200,
    beatFreq: 14,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 14 Hz',
    defaultDuration: 25,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.beta,
  },
];

export function getPresetsByCategory(category: PresetCategory | 'all'): Preset[] {
  if (category === 'all') return PRESETS;
  return PRESETS.filter((p) => p.category === category);
}

export function getPresetById(id: string): Preset | undefined {
  return PRESETS.find((p) => p.id === id);
}
