import type { Preset, PresetCategory } from '@/types';
import { BRAINWAVE_COLORS } from './constants';

export const PRESETS: Preset[] = [
  // Focus (Beta/Gamma)
  {
    id: 'deep-focus',
    name: 'Deep Focus',
    category: 'focus',
    icon: '\u{1F9E0}',
    description: 'Sustained concentration for deep work',
    carrierFreq: 200,
    beatFreq: 16,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 16 Hz',
    defaultDuration: 25,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.beta,
  },
  {
    id: 'study-flow',
    name: 'Study Flow',
    category: 'focus',
    icon: '\u{1F9E0}',
    description: 'Background focus for reading and study',
    carrierFreq: 250,
    beatFreq: 14,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 14 Hz',
    defaultDuration: 45,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.beta,
  },
  {
    id: 'creative-spark',
    name: 'Creative Spark',
    category: 'focus',
    icon: '\u{1F9E0}',
    description: 'Open, creative thinking and ideation',
    carrierFreq: 180,
    beatFreq: 10,
    brainwaveState: 'alpha',
    brainwaveLabel: 'Alpha \u00B7 10 Hz',
    defaultDuration: 20,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.alpha,
  },
  {
    id: 'problem-solving',
    name: 'Problem Solving',
    category: 'focus',
    icon: '\u{1F9E0}',
    description: 'Heightened information processing',
    carrierFreq: 220,
    beatFreq: 40,
    brainwaveState: 'gamma',
    brainwaveLabel: 'Gamma \u00B7 40 Hz',
    defaultDuration: 15,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.gamma,
  },

  // Sleep (Delta/Theta)
  {
    id: 'fall-asleep',
    name: 'Fall Asleep',
    category: 'sleep',
    icon: '\u{1F634}',
    description: 'Gentle descent into sleep',
    carrierFreq: 150,
    beatFreq: 3,
    brainwaveState: 'delta',
    brainwaveLabel: 'Delta \u00B7 3 Hz',
    defaultDuration: 30,
    fadeIn: 3,
    fadeOut: 2,
    color: BRAINWAVE_COLORS.delta,
  },
  {
    id: 'deep-sleep',
    name: 'Deep Sleep',
    category: 'sleep',
    icon: '\u{1F634}',
    description: 'Sustained deep, dreamless sleep',
    carrierFreq: 120,
    beatFreq: 1.5,
    brainwaveState: 'delta',
    brainwaveLabel: 'Delta \u00B7 1.5 Hz',
    defaultDuration: 60,
    fadeIn: 3,
    fadeOut: 2,
    color: BRAINWAVE_COLORS.delta,
  },
  {
    id: 'power-nap',
    name: 'Power Nap',
    category: 'sleep',
    icon: '\u{1F634}',
    description: 'Quick restorative rest',
    carrierFreq: 180,
    beatFreq: 5,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 5 Hz',
    defaultDuration: 20,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'insomnia-relief',
    name: 'Insomnia Relief',
    category: 'sleep',
    icon: '\u{1F634}',
    description: 'Calm a racing mind for sleep',
    carrierFreq: 136,
    beatFreq: 2.5,
    brainwaveState: 'delta',
    brainwaveLabel: 'Delta \u00B7 2.5 Hz',
    defaultDuration: 45,
    fadeIn: 3,
    fadeOut: 2,
    color: BRAINWAVE_COLORS.delta,
  },

  // Meditation (Theta/Alpha)
  {
    id: 'mindfulness',
    name: 'Mindfulness',
    category: 'meditation',
    icon: '\u{1F9D8}',
    description: 'Present-moment awareness',
    carrierFreq: 200,
    beatFreq: 7,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 7 Hz',
    defaultDuration: 20,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'transcendental',
    name: 'Transcendental',
    category: 'meditation',
    icon: '\u{1F9D8}',
    description: 'Deep transcendent meditation',
    carrierFreq: 136,
    beatFreq: 4.5,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 4.5 Hz',
    defaultDuration: 30,
    fadeIn: 3,
    fadeOut: 2,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'loving-kindness',
    name: 'Loving Kindness',
    category: 'meditation',
    icon: '\u{1F9D8}',
    description: 'Heart-centred compassion practice',
    carrierFreq: 264,
    beatFreq: 8,
    brainwaveState: 'alpha',
    brainwaveLabel: 'Alpha \u00B7 8 Hz',
    defaultDuration: 15,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.alpha,
  },
  {
    id: 'body-scan',
    name: 'Body Scan',
    category: 'meditation',
    icon: '\u{1F9D8}',
    description: 'Progressive body awareness',
    carrierFreq: 180,
    beatFreq: 6,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 6 Hz',
    defaultDuration: 25,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.theta,
  },

  // Relaxation (Alpha/Theta)
  {
    id: 'stress-relief',
    name: 'Stress Relief',
    category: 'relaxation',
    icon: '\u{1F60C}',
    description: 'Rapid stress reduction',
    carrierFreq: 200,
    beatFreq: 10,
    brainwaveState: 'alpha',
    brainwaveLabel: 'Alpha \u00B7 10 Hz',
    defaultDuration: 15,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.alpha,
  },
  {
    id: 'anxiety-calm',
    name: 'Anxiety Calm',
    category: 'relaxation',
    icon: '\u{1F60C}',
    description: 'Soothe anxious thoughts',
    carrierFreq: 170,
    beatFreq: 7.5,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 7.5 Hz',
    defaultDuration: 20,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'tension-release',
    name: 'Tension Release',
    category: 'relaxation',
    icon: '\u{1F60C}',
    description: 'Physical and mental tension relief',
    carrierFreq: 150,
    beatFreq: 5.5,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 5.5 Hz',
    defaultDuration: 15,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'wind-down',
    name: 'Wind Down',
    category: 'relaxation',
    icon: '\u{1F60C}',
    description: 'Evening transition to rest',
    carrierFreq: 190,
    beatFreq: 9,
    brainwaveState: 'alpha',
    brainwaveLabel: 'Alpha \u00B7 9 Hz',
    defaultDuration: 20,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.alpha,
  },

  // Energy (Beta/Gamma)
  {
    id: 'morning-boost',
    name: 'Morning Boost',
    category: 'energy',
    icon: '\u{26A1}',
    description: 'Energise your morning',
    carrierFreq: 250,
    beatFreq: 18,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 18 Hz',
    defaultDuration: 10,
    fadeIn: 1.5,
    fadeOut: 1,
    color: BRAINWAVE_COLORS.beta,
  },
  {
    id: 'afternoon-revival',
    name: 'Afternoon Revival',
    category: 'energy',
    icon: '\u{26A1}',
    description: 'Beat the afternoon slump',
    carrierFreq: 230,
    beatFreq: 15,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 15 Hz',
    defaultDuration: 10,
    fadeIn: 1.5,
    fadeOut: 1,
    color: BRAINWAVE_COLORS.beta,
  },
  {
    id: 'pre-workout',
    name: 'Pre-Workout',
    category: 'energy',
    icon: '\u{26A1}',
    description: 'Physical activation and drive',
    carrierFreq: 280,
    beatFreq: 25,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 25 Hz',
    defaultDuration: 10,
    fadeIn: 1.5,
    fadeOut: 1,
    color: BRAINWAVE_COLORS.beta,
  },
  {
    id: 'confidence',
    name: 'Confidence',
    category: 'energy',
    icon: '\u{26A1}',
    description: 'Self-assurance and presence',
    carrierFreq: 200,
    beatFreq: 20,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 20 Hz',
    defaultDuration: 15,
    fadeIn: 1.5,
    fadeOut: 1,
    color: BRAINWAVE_COLORS.beta,
  },

  // Therapy (Various)
  {
    id: 'pain-relief',
    name: 'Pain Relief',
    category: 'therapy',
    icon: '\u{1F3AF}',
    description: 'Frequency support for pain management',
    carrierFreq: 174,
    beatFreq: 4,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 4 Hz',
    defaultDuration: 30,
    fadeIn: 3,
    fadeOut: 2,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'headache-ease',
    name: 'Headache Ease',
    category: 'therapy',
    icon: '\u{1F3AF}',
    description: 'Soothing relief for headaches',
    carrierFreq: 160,
    beatFreq: 6,
    brainwaveState: 'theta',
    brainwaveLabel: 'Theta \u00B7 6 Hz',
    defaultDuration: 15,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.theta,
  },
  {
    id: 'tinnitus-mask',
    name: 'Tinnitus Mask',
    category: 'therapy',
    icon: '\u{1F3AF}',
    description: 'Gentle masking for tinnitus',
    carrierFreq: 400,
    beatFreq: 10,
    brainwaveState: 'alpha',
    brainwaveLabel: 'Alpha \u00B7 10 Hz',
    defaultDuration: 30,
    fadeIn: 3,
    fadeOut: 2,
    color: BRAINWAVE_COLORS.alpha,
  },
  {
    id: 'adhd-focus',
    name: 'ADHD Focus',
    category: 'therapy',
    icon: '\u{1F3AF}',
    description: 'Sustained attention support',
    carrierFreq: 200,
    beatFreq: 14,
    brainwaveState: 'beta',
    brainwaveLabel: 'Beta \u00B7 14 Hz',
    defaultDuration: 25,
    fadeIn: 2,
    fadeOut: 1.5,
    color: BRAINWAVE_COLORS.beta,
  },

  // ═══════════════════════════════════════════════════════════
  // INTERVALS — Musical Harmonic Relationships (13 presets)
  // ═══════════════════════════════════════════════════════════

  {
    id: 'unison',
    name: 'Unison',
    category: 'intervals',
    icon: '\u{269B}\u{FE0F}',
    description: 'Pure unity \u2014 both ears in perfect synchrony',
    carrierFreq: 136.1,
    beatFreq: 0,
    rightFreq: 136.1,
    intervalName: 'Unison',
    intervalRatio: '1:1',
    ratioNumerator: 1,
    ratioDenominator: 1,
    brainwaveState: 'harmony',
    brainwaveLabel: 'Unison \u00B7 1:1',
    defaultDuration: 15,
    fadeIn: 8,
    fadeOut: 8,
    color: '#FFFFFF',
  },
  {
    id: 'minor-second',
    name: 'Minor Second',
    category: 'intervals',
    icon: '\u{1F30A}',
    description: 'Gentle tension \u2014 the smallest step, a whisper of movement',
    carrierFreq: 240,
    beatFreq: 16,
    rightFreq: 256,
    intervalName: 'Minor Second',
    intervalRatio: '15:16',
    ratioNumerator: 15,
    ratioDenominator: 16,
    brainwaveState: 'harmony',
    brainwaveLabel: 'Minor Second \u00B7 15:16',
    defaultDuration: 10,
    fadeIn: 5,
    fadeOut: 5,
    color: '#6366F1',
  },
  {
    id: 'major-second',
    name: 'Major Second',
    category: 'intervals',
    icon: '\u{1F343}',
    description: 'A gentle step \u2014 building energy with natural momentum',
    carrierFreq: 256,
    beatFreq: 32,
    rightFreq: 288,
    intervalName: 'Major Second',
    intervalRatio: '8:9',
    ratioNumerator: 8,
    ratioDenominator: 9,
    brainwaveState: 'harmony',
    brainwaveLabel: 'Major Second \u00B7 8:9',
    defaultDuration: 12,
    fadeIn: 5,
    fadeOut: 5,
    color: '#22D3EE',
  },
  {
    id: 'minor-third',
    name: 'Minor Third',
    category: 'intervals',
    icon: '\u{1F319}',
    description: 'Tender and reflective \u2014 the interval of introspection',
    carrierFreq: 200,
    beatFreq: 40,
    rightFreq: 240,
    intervalName: 'Minor Third',
    intervalRatio: '5:6',
    ratioNumerator: 5,
    ratioDenominator: 6,
    brainwaveState: 'harmony',
    brainwaveLabel: 'Minor Third \u00B7 5:6',
    defaultDuration: 15,
    fadeIn: 6,
    fadeOut: 6,
    color: '#818CF8',
  },
  {
    id: 'major-third',
    name: 'Major Third',
    category: 'intervals',
    icon: '\u{1F338}',
    description: 'Warm and uplifting \u2014 the interval of joy and brightness',
    carrierFreq: 200,
    beatFreq: 50,
    rightFreq: 250,
    intervalName: 'Major Third',
    intervalRatio: '4:5',
    ratioNumerator: 4,
    ratioDenominator: 5,
    brainwaveState: 'harmony',
    brainwaveLabel: 'Major Third \u00B7 4:5',
    defaultDuration: 15,
    fadeIn: 6,
    fadeOut: 6,
    color: '#F59E0B',
  },
  {
    id: 'perfect-fourth',
    name: 'Perfect Fourth',
    category: 'intervals',
    icon: '\u{1F9D8}',
    description: 'Stable and grounding \u2014 used in sacred music for millennia',
    carrierFreq: 192,
    beatFreq: 64,
    rightFreq: 256,
    intervalName: 'Perfect Fourth',
    intervalRatio: '3:4',
    ratioNumerator: 3,
    ratioDenominator: 4,
    brainwaveState: 'harmony',
    brainwaveLabel: 'Perfect Fourth \u00B7 3:4',
    defaultDuration: 20,
    fadeIn: 8,
    fadeOut: 8,
    color: '#10B981',
  },
  {
    id: 'tritone',
    name: 'Tritone',
    category: 'intervals',
    icon: '\u{1F525}',
    description: 'The devil\'s interval \u2014 powerful tension seeking resolution',
    carrierFreq: 256,
    beatFreq: 104,
    rightFreq: 360,
    intervalName: 'Tritone',
    intervalRatio: '32:45',
    ratioNumerator: 32,
    ratioDenominator: 45,
    brainwaveState: 'harmony',
    brainwaveLabel: 'Tritone \u00B7 32:45',
    defaultDuration: 10,
    fadeIn: 5,
    fadeOut: 5,
    color: '#EF4444',
  },
  {
    id: 'perfect-fifth',
    name: 'Perfect Fifth',
    category: 'intervals',
    icon: '\u2726',
    description: 'The most consonant interval \u2014 pure harmonic resonance',
    carrierFreq: 200,
    beatFreq: 100,
    rightFreq: 300,
    intervalName: 'Perfect Fifth',
    intervalRatio: '2:3',
    ratioNumerator: 2,
    ratioDenominator: 3,
    brainwaveState: 'harmony',
    brainwaveLabel: 'Perfect Fifth \u00B7 2:3',
    defaultDuration: 20,
    fadeIn: 8,
    fadeOut: 8,
    color: '#8B5CF6',
  },
  {
    id: 'minor-sixth',
    name: 'Minor Sixth',
    category: 'intervals',
    icon: '\u{1F98B}',
    description: 'Bittersweet and yearning \u2014 beauty through gentle tension',
    carrierFreq: 200,
    beatFreq: 120,
    rightFreq: 320,
    intervalName: 'Minor Sixth',
    intervalRatio: '5:8',
    ratioNumerator: 5,
    ratioDenominator: 8,
    brainwaveState: 'harmony',
    brainwaveLabel: 'Minor Sixth \u00B7 5:8',
    defaultDuration: 15,
    fadeIn: 6,
    fadeOut: 6,
    color: '#A78BFA',
  },
  {
    id: 'major-sixth',
    name: 'Major Sixth',
    category: 'intervals',
    icon: '\u{1F49B}',
    description: 'Sweet and expansive \u2014 opens the heart space',
    carrierFreq: 180,
    beatFreq: 120,
    rightFreq: 300,
    intervalName: 'Major Sixth',
    intervalRatio: '3:5',
    ratioNumerator: 3,
    ratioDenominator: 5,
    brainwaveState: 'harmony',
    brainwaveLabel: 'Major Sixth \u00B7 3:5',
    defaultDuration: 15,
    fadeIn: 6,
    fadeOut: 6,
    color: '#EC4899',
  },
  {
    id: 'minor-seventh',
    name: 'Minor Seventh',
    category: 'intervals',
    icon: '\u{1F30C}',
    description: 'Soulful and searching \u2014 rich with harmonic complexity',
    carrierFreq: 200,
    beatFreq: 160,
    rightFreq: 360,
    intervalName: 'Minor Seventh',
    intervalRatio: '5:9',
    ratioNumerator: 5,
    ratioDenominator: 9,
    brainwaveState: 'harmony',
    brainwaveLabel: 'Minor Seventh \u00B7 5:9',
    defaultDuration: 15,
    fadeIn: 6,
    fadeOut: 6,
    color: '#7C3AED',
  },
  {
    id: 'major-seventh',
    name: 'Major Seventh',
    category: 'intervals',
    icon: '\u2728',
    description: 'Dreamy and ethereal \u2014 shimmering on the edge of resolution',
    carrierFreq: 192,
    beatFreq: 168,
    rightFreq: 360,
    intervalName: 'Major Seventh',
    intervalRatio: '8:15',
    ratioNumerator: 8,
    ratioDenominator: 15,
    brainwaveState: 'harmony',
    brainwaveLabel: 'Major Seventh \u00B7 8:15',
    defaultDuration: 12,
    fadeIn: 6,
    fadeOut: 6,
    color: '#F0ABFC',
  },
  {
    id: 'octave',
    name: 'Octave',
    category: 'intervals',
    icon: '\u{1F52E}',
    description: 'Complete doubling \u2014 the same note expanded into fullness',
    carrierFreq: 174,
    beatFreq: 174,
    rightFreq: 348,
    intervalName: 'Octave',
    intervalRatio: '1:2',
    ratioNumerator: 1,
    ratioDenominator: 2,
    brainwaveState: 'harmony',
    brainwaveLabel: 'Octave \u00B7 1:2',
    defaultDuration: 15,
    fadeIn: 8,
    fadeOut: 8,
    color: '#06B6D4',
  },
];

export function getPresetsByCategory(category: PresetCategory | 'all' | 'favourites', favouriteIds?: string[]): Preset[] {
  if (category === 'favourites') {
    if (!favouriteIds || favouriteIds.length === 0) return [];
    return PRESETS.filter((p) => favouriteIds.includes(p.id));
  }
  if (category === 'all') return PRESETS;
  return PRESETS.filter((p) => p.category === category);
}

export function getPresetById(id: string): Preset | undefined {
  return PRESETS.find((p) => p.id === id);
}
